In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**How to create a null values in a data**

- None
- np.nan

In [2]:
d={'Names':['Ramesh','Suresh',None,'Sathish'],
   'Age':[None,20,21,24],
   'City':['Hyd','Blr','Pune',None]}
df=pd.DataFrame(d)
df

     Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  20.0   Blr
2     None  21.0  Pune
3  Sathish  24.0  None

In [3]:
df.to_csv('data1.csv',index=False)

In [4]:
d={'Names':['Ramesh','Suresh',np.nan,'Sathish'],
   'Age':[np.nan,20,21,24],
   'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2
df2.to_csv('data2.csv',index=False)

- categorical data use **None**
- numerical data use **np.nan**

In [6]:
df.isnull()
# isnull = whereever null value is there it displays as true

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [7]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [8]:
df.values

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 20.0, 'Blr'],
       [None, 21.0, 'Pune'],
       ['Sathish', 24.0, None]], dtype=object)

In [9]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

**Fill the values**

In [12]:
df.fillna(30)
# it is a random values

     Names   Age  City
0   Ramesh  30.0   Hyd
1   Suresh  20.0   Blr
2       30  21.0  Pune
3  Sathish  24.0    30

In [11]:
df

     Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  20.0   Blr
2     None  21.0  Pune
3  Sathish  24.0  None

In [18]:
# select the column and fill with value
df['Age'].fillna(30)

0    30.0
1    20.0
2    21.0
3    24.0
Name: Age, dtype: float64

In [ ]:
df['Age'].fillna(df['Age'].mean())

In [19]:
#pad,ffill,bfill,backfill
#axis=0,axis=1
df.fillna(method='pad')

C:\Users\jayavardhan\AppData\Local\Temp\ipykernel_26200\2927640253.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

     Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  20.0   Blr
2   Suresh  21.0  Pune
3  Sathish  24.0  Pune

In [20]:
df.fillna(method='ffill')

C:\Users\jayavardhan\AppData\Local\Temp\ipykernel_26200\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  20.0   Blr
2   Suresh  21.0  Pune
3  Sathish  24.0  Pune

In [21]:
df.fillna(method='bfill')

C:\Users\jayavardhan\AppData\Local\Temp\ipykernel_26200\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

     Names   Age  City
0   Ramesh  20.0   Hyd
1   Suresh  20.0   Blr
2  Sathish  21.0  Pune
3  Sathish  24.0  None

In [22]:
df.fillna(method='backfill')

C:\Users\jayavardhan\AppData\Local\Temp\ipykernel_26200\340531938.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='backfill')

     Names   Age  City
0   Ramesh  20.0   Hyd
1   Suresh  20.0   Blr
2  Sathish  21.0  Pune
3  Sathish  24.0  None

In [23]:
df.fillna(df['City'].bfill())

     Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  20.0   Blr
2     None  21.0  Pune
3  Sathish  24.0  None

In [24]:
df.fillna(method='bfill',axis=1)

C:\Users\jayavardhan\AppData\Local\Temp\ipykernel_26200\3381026564.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',axis=1)

     Names   Age  City
0   Ramesh   Hyd   Hyd
1   Suresh  20.0   Blr
2     21.0  21.0  Pune
3  Sathish  24.0  None

In [25]:
df

     Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  20.0   Blr
2     None  21.0  Pune
3  Sathish  24.0  None

In [28]:
df['Age'].fillna(round(df['Age'].mean(),1))

0    21.7
1    20.0
2    21.0
3    24.0
Name: Age, dtype: float64

In [27]:
df['Age'].fillna(df['Age'].median())

0    21.0
1    20.0
2    21.0
3    24.0
Name: Age, dtype: float64

In [ ]:
#there is no particular rules to fill null values
#It is completely based on situation

In [29]:
Gender=['male','female',None,'male']
df=pd.DataFrame(Gender)
df

        0
0    male
1  female
2    None
3    male

In [32]:
df.fillna(df[0].mode())

        0
0    male
1  female
2    male
3    male

In [33]:
d={'Names':['Ramesh','Suresh','Ramesh','Sathish'],
   'Age':[21,20,21,24],
   'City':['Hyd','Blr','Hyd','pune']}
df=pd.DataFrame(d)
df

     Names  Age  City
0   Ramesh   21   Hyd
1   Suresh   20   Blr
2   Ramesh   21   Hyd
3  Sathish   24  pune

In [35]:
df.duplicated().sum()

np.int64(1)

In [38]:
df.drop(2)

     Names  Age  City
0   Ramesh   21   Hyd
1   Suresh   20   Blr
3  Sathish   24  pune

**KNNImputer**

- KNN : K-nearest neighbours
- where k is a number
- insted of taking avg of all the values data
    - first will find the neighbours who are close with missing data
    - by using euclidian distance calculation will identify the neighbours rows
    - suppose k=2 will identify two closeset rows
    - those closest row values will take it will calculate the mean
    - finally will fill with the mean

In [40]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

In [43]:
from sklearn.impute import KNNImputer
kn=KNNImputer(n_neighbors=2)
pd.DataFrame(kn.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0